parent=keycloak
import=common/keycloak
styles=css/login.css css/styles.css
scripts=js/scripts.js

# Missing themes/keycloak/login/theme.properties from Keycloak 9.0.2
kcContentWrapperClass=row
kcFormSocialAccountClass=login-pf-social-section
kcFormSocialAccountContentClass=col-xs-12 col-sm-6
kcFormSocialAccountListLinkClass=login-pf-social-link